accordion-padding = 30
after-startup-command = []
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
exec-on-workspace-change = []
on-focus-changed = []
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
on-window-detected = []
start-at-login = true

[gaps.inner]
horizontal = 8
vertical = 8

[gaps.outer]
bottom = 8
left = 8
right = 8
top = 8

[key-mapping]
preset = "qwerty"

[mode.main.binding]
alt-a = "workspace A"
alt-b = "workspace B"
alt-c = "workspace C"
alt-d = "workspace D"
alt-e = "workspace E"
alt-f = "workspace F"
alt-g = "workspace G"
alt-h = "focus left"
alt-i = "workspace I"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"
alt-m = "workspace M"
alt-n = "workspace N"
alt-o = "workspace O"
alt-p = "workspace P"
alt-q = "workspace Q"
alt-r = "workspace R"
alt-s = "workspace S"
alt-shift-a = "move-node-to-workspace A"
alt-shift-b = "move-node-to-workspace B"
alt-shift-c = "move-node-to-workspace C"
alt-shift-comma = "mode service"
alt-shift-d = "move-node-to-workspace D"
alt-shift-e = "move-node-to-workspace E"
alt-shift-equal = "resize smart +50"
alt-shift-f = "move-node-to-workspace F"
alt-shift-g = "move-node-to-workspace G"
alt-shift-h = "move left"
alt-shift-i = "move-node-to-workspace I"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"
alt-shift-m = "move-node-to-workspace M"
alt-shift-minus = "resize smart -50"
alt-shift-n = "move-node-to-workspace N"
alt-shift-o = "move-node-to-workspace O"
alt-shift-p = "move-node-to-workspace P"
alt-shift-q = "move-node-to-workspace Q"
alt-shift-r = "move-node-to-workspace R"
alt-shift-s = "move-node-to-workspace S"
alt-shift-t = "move-node-to-workspace T"
alt-shift-tab = "move-workspace-to-monitor --wrap-around next"
alt-shift-u = "move-node-to-workspace U"
alt-shift-v = "move-node-to-workspace V"
alt-shift-w = "move-node-to-workspace W"
alt-shift-x = "move-node-to-workspace X"
alt-shift-y = "move-node-to-workspace Y"
alt-shift-z = "move-node-to-workspace Z"
alt-t = "workspace T"
alt-u = "workspace U"
alt-v = "workspace V"
alt-w = "workspace W"
alt-x = "workspace X"
alt-y = "workspace Y"
alt-z = "workspace Z"

[mode.service.binding]
alt-shift-h = ["join-with left", "mode main"]
alt-shift-j = ["join-with down", "mode main"]
alt-shift-k = ["join-with up", "mode main"]
alt-shift-l = ["join-with right", "mode main"]
backspace = ["close-all-windows-but-current", "mode main"]
esc = ["reload-config", "mode main"]
f = ["layout floating tiling", "mode main"]
r = ["flatten-workspace-tree", "mode main"]

[workspace-to-monitor-force-assignment]
A = "main"
D = "main"
E = "secondary"
F = "main"
G = "main"
Q = "secondary"
R = "secondary"
S = "main"
W = "secondary"
